// **********************************************************************
//
// Copyright (c) 2003-2010 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************

// Ice version 3.4.0

package drakkar.oar.slice.client;

// <auto-generated>
//
// Generated from file `ClientSide.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>


public interface _ClientSideDel extends drakkar.oar.slice.action.twoway._GetDel
{
    void _notify(byte[] response, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    void disconnect(java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;
}
