// **********************************************************************
//
// Copyright (c) 2003-2010 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************

// Ice version 3.4.0

package drakkar.oar.slice.client;

// <auto-generated>
//
// Generated from file `ClientSide.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>


public final class ClientSidePrxHolder
{
    public
    ClientSidePrxHolder()
    {
    }

    public
    ClientSidePrxHolder(ClientSidePrx value)
    {
        this.value = value;
    }

    public ClientSidePrx value;
}
