// **********************************************************************
//
// Copyright (c) 2003-2010 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************

// Ice version 3.4.0

package drakkar.oar.slice.transfer;

// <auto-generated>
//
// Generated from file `FileTransfer.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>


public interface _FileStoreDel extends Ice._ObjectDel
{
    FilePrx read(String name, int num, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper,
               FileAccessException;

    void write(String name, int offset, byte[] bytes, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;
}
