// **********************************************************************
//
// Copyright (c) 2003-2010 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************

// Ice version 3.4.0

package drakkar.oar.slice.transfer;

// <auto-generated>
//
// Generated from file `FileTransfer.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>


public interface FilePrx extends Ice.ObjectPrx
{
    public byte[] next();

    public byte[] next(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_next();

    public Ice.AsyncResult begin_next(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_next(Ice.Callback __cb);

    public Ice.AsyncResult begin_next(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_next(Callback_File_next __cb);

    public Ice.AsyncResult begin_next(java.util.Map<String, String> __ctx, Callback_File_next __cb);

    public byte[] end_next(Ice.AsyncResult __result);

    public boolean next_async(AMI_File_next __cb);

    public boolean next_async(AMI_File_next __cb, java.util.Map<String, String> __ctx);
}
