// **********************************************************************
//
// Copyright (c) 2003-2010 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************

// Ice version 3.4.0

package drakkar.oar.slice.error;

// <auto-generated>
//
// Generated from file `Exception.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>


public class RequestException extends Ice.UserException
{
    public RequestException()
    {
    }

    public RequestException(String reason)
    {
        this.reason = reason;
    }

    public String
    ice_name()
    {
        return "drakkar::oar::slice::error::RequestException";
    }

    public String reason;

    public void
    __write(IceInternal.BasicStream __os)
    {
        __os.writeString("::drakkar::oar::slice::error::RequestException");
        __os.startWriteSlice();
        __os.writeString(reason);
        __os.endWriteSlice();
    }

    public void
    __read(IceInternal.BasicStream __is, boolean __rid)
    {
        if(__rid)
        {
            __is.readString();
        }
        __is.startReadSlice();
        reason = __is.readString();
        __is.endReadSlice();
    }

    public void
    __write(Ice.OutputStream __outS)
    {
        Ice.MarshalException ex = new Ice.MarshalException();
        ex.reason = "exception drakkar::oar::slice::error::RequestException was not generated with stream support";
        throw ex;
    }

    public void
    __read(Ice.InputStream __inS, boolean __rid)
    {
        Ice.MarshalException ex = new Ice.MarshalException();
        ex.reason = "exception drakkar::oar::slice::error::RequestException was not generated with stream support";
        throw ex;
    }
}
