// **********************************************************************
//
// Copyright (c) 2003-2010 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************

// Ice version 3.4.0

package drakkar.oar.slice.login;

// <auto-generated>
//
// Generated from file `Authentication.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>


public interface _AuthenticationOperations extends drakkar.oar.slice.action._RCPOperationsOperations
{
    drakkar.oar.Seeker login(byte[] request, Ice.Current __current)
        throws drakkar.oar.slice.error.RequestException;

    boolean logout(drakkar.oar.Seeker memb, Ice.Current __current)
        throws drakkar.oar.slice.error.RequestException;
}
