// **********************************************************************
//
// Copyright (c) 2003-2010 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************

// Ice version 3.4.0

package drakkar.oar.slice.login;

// <auto-generated>
//
// Generated from file `InRole.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>


public abstract class _RoleDisp extends Ice.ObjectImpl implements Role
{
    protected void
    ice_copyStateFrom(Ice.Object __obj)
        throws java.lang.CloneNotSupportedException
    {
        throw new java.lang.CloneNotSupportedException();
    }

    public static final String[] __ids =
    {
        "::Ice::Object",
        "::drakkar::oar::slice::login::Role"
    };

    public boolean
    ice_isA(String s)
    {
        return java.util.Arrays.binarySearch(__ids, s) >= 0;
    }

    public boolean
    ice_isA(String s, Ice.Current __current)
    {
        return java.util.Arrays.binarySearch(__ids, s) >= 0;
    }

    public String[]
    ice_ids()
    {
        return __ids;
    }

    public String[]
    ice_ids(Ice.Current __current)
    {
        return __ids;
    }

    public String
    ice_id()
    {
        return __ids[1];
    }

    public String
    ice_id(Ice.Current __current)
    {
        return __ids[1];
    }

    public static String
    ice_staticId()
    {
        return __ids[1];
    }

    public final void
    disconnect()
    {
        disconnect(null);
    }

    public final void
    login(drakkar.oar.Seeker memb, drakkar.oar.slice.client.ClientSidePrx client, drakkar.oar.slice.server.ServerSidePrxHolder server)
        throws drakkar.oar.slice.error.RequestException
    {
        login(memb, client, server, null);
    }

    public static Ice.DispatchStatus
    ___login(Role __obj, IceInternal.Incoming __inS, Ice.Current __current)
    {
        __checkMode(Ice.OperationMode.Normal, __current.mode);
        IceInternal.BasicStream __is = __inS.is();
        __is.startReadEncaps();
        drakkar.oar.Seeker memb;
        memb = (drakkar.oar.Seeker)__is.readSerializable();
        drakkar.oar.slice.client.ClientSidePrx client;
        client = drakkar.oar.slice.client.ClientSidePrxHelper.__read(__is);
        __is.endReadEncaps();
        drakkar.oar.slice.server.ServerSidePrxHolder server = new drakkar.oar.slice.server.ServerSidePrxHolder();
        IceInternal.BasicStream __os = __inS.os();
        try
        {
            __obj.login(memb, client, server, __current);
            drakkar.oar.slice.server.ServerSidePrxHelper.__write(__os, server.value);
            return Ice.DispatchStatus.DispatchOK;
        }
        catch(drakkar.oar.slice.error.RequestException ex)
        {
            __os.writeUserException(ex);
            return Ice.DispatchStatus.DispatchUserException;
        }
    }

    public static Ice.DispatchStatus
    ___disconnect(Role __obj, IceInternal.Incoming __inS, Ice.Current __current)
    {
        __checkMode(Ice.OperationMode.Normal, __current.mode);
        __inS.is().skipEmptyEncaps();
        __obj.disconnect(__current);
        return Ice.DispatchStatus.DispatchOK;
    }

    private final static String[] __all =
    {
        "disconnect",
        "ice_id",
        "ice_ids",
        "ice_isA",
        "ice_ping",
        "login"
    };

    public Ice.DispatchStatus
    __dispatch(IceInternal.Incoming in, Ice.Current __current)
    {
        int pos = java.util.Arrays.binarySearch(__all, __current.operation);
        if(pos < 0)
        {
            throw new Ice.OperationNotExistException(__current.id, __current.facet, __current.operation);
        }

        switch(pos)
        {
            case 0:
            {
                return ___disconnect(this, in, __current);
            }
            case 1:
            {
                return ___ice_id(this, in, __current);
            }
            case 2:
            {
                return ___ice_ids(this, in, __current);
            }
            case 3:
            {
                return ___ice_isA(this, in, __current);
            }
            case 4:
            {
                return ___ice_ping(this, in, __current);
            }
            case 5:
            {
                return ___login(this, in, __current);
            }
        }

        assert(false);
        throw new Ice.OperationNotExistException(__current.id, __current.facet, __current.operation);
    }

    public void
    __write(IceInternal.BasicStream __os)
    {
        __os.writeTypeId(ice_staticId());
        __os.startWriteSlice();
        __os.endWriteSlice();
        super.__write(__os);
    }

    public void
    __read(IceInternal.BasicStream __is, boolean __rid)
    {
        if(__rid)
        {
            __is.readTypeId();
        }
        __is.startReadSlice();
        __is.endReadSlice();
        super.__read(__is, true);
    }

    public void
    __write(Ice.OutputStream __outS)
    {
        Ice.MarshalException ex = new Ice.MarshalException();
        ex.reason = "type drakkar::oar::slice::login::Role was not generated with stream support";
        throw ex;
    }

    public void
    __read(Ice.InputStream __inS, boolean __rid)
    {
        Ice.MarshalException ex = new Ice.MarshalException();
        ex.reason = "type drakkar::oar::slice::login::Role was not generated with stream support";
        throw ex;
    }
}
