// **********************************************************************
//
// Copyright (c) 2003-2010 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************

// Ice version 3.4.0

package drakkar.oar.slice.login;

// <auto-generated>
//
// Generated from file `InRole.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>


public interface _RoleOperations
{
    void login(drakkar.oar.Seeker memb, drakkar.oar.slice.client.ClientSidePrx client, drakkar.oar.slice.server.ServerSidePrxHolder server, Ice.Current __current)
        throws drakkar.oar.slice.error.RequestException;

    void disconnect(Ice.Current __current);
}
