// **********************************************************************
//
// Copyright (c) 2003-2010 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************

// Ice version 3.4.0

package drakkar.oar.slice.login;

// <auto-generated>
//
// Generated from file `Authentication.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>


public interface AuthenticationPrx extends drakkar.oar.slice.action.RCPOperationsPrx
{
    public drakkar.oar.Seeker login(byte[] request)
        throws drakkar.oar.slice.error.RequestException;

    public drakkar.oar.Seeker login(byte[] request, java.util.Map<String, String> __ctx)
        throws drakkar.oar.slice.error.RequestException;

    public Ice.AsyncResult begin_login(byte[] request);

    public Ice.AsyncResult begin_login(byte[] request, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_login(byte[] request, Ice.Callback __cb);

    public Ice.AsyncResult begin_login(byte[] request, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_login(byte[] request, Callback_Authentication_login __cb);

    public Ice.AsyncResult begin_login(byte[] request, java.util.Map<String, String> __ctx, Callback_Authentication_login __cb);

    public drakkar.oar.Seeker end_login(Ice.AsyncResult __result)
        throws drakkar.oar.slice.error.RequestException;

    public boolean logout(drakkar.oar.Seeker memb)
        throws drakkar.oar.slice.error.RequestException;

    public boolean logout(drakkar.oar.Seeker memb, java.util.Map<String, String> __ctx)
        throws drakkar.oar.slice.error.RequestException;

    public Ice.AsyncResult begin_logout(drakkar.oar.Seeker memb);

    public Ice.AsyncResult begin_logout(drakkar.oar.Seeker memb, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_logout(drakkar.oar.Seeker memb, Ice.Callback __cb);

    public Ice.AsyncResult begin_logout(drakkar.oar.Seeker memb, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_logout(drakkar.oar.Seeker memb, Callback_Authentication_logout __cb);

    public Ice.AsyncResult begin_logout(drakkar.oar.Seeker memb, java.util.Map<String, String> __ctx, Callback_Authentication_logout __cb);

    public boolean end_logout(Ice.AsyncResult __result)
        throws drakkar.oar.slice.error.RequestException;
}
