// **********************************************************************
//
// Copyright (c) 2003-2010 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************

// Ice version 3.4.0

package drakkar.oar.slice.login;

// <auto-generated>
//
// Generated from file `InRole.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>


public abstract class Callback_Role_login extends Ice.TwowayCallback
{
    public abstract void response(drakkar.oar.slice.server.ServerSidePrx server);
    public abstract void exception(Ice.UserException __ex);

    public final void __completed(Ice.AsyncResult __result)
    {
        RolePrx __proxy = (RolePrx)__result.getProxy();
        drakkar.oar.slice.server.ServerSidePrxHolder server = new drakkar.oar.slice.server.ServerSidePrxHolder();
        try
        {
            __proxy.end_login(server, __result);
        }
        catch(Ice.UserException __ex)
        {
            exception(__ex);
            return;
        }
        catch(Ice.LocalException __ex)
        {
            exception(__ex);
            return;
        }
        response(server.value);
    }
}
