// **********************************************************************
//
// Copyright (c) 2003-2010 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************

// Ice version 3.4.0

package drakkar.oar.slice.login;

// <auto-generated>
//
// Generated from file `InRole.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>


public interface RolePrx extends Ice.ObjectPrx
{
    public void login(drakkar.oar.Seeker memb, drakkar.oar.slice.client.ClientSidePrx client, drakkar.oar.slice.server.ServerSidePrxHolder server)
        throws drakkar.oar.slice.error.RequestException;

    public void login(drakkar.oar.Seeker memb, drakkar.oar.slice.client.ClientSidePrx client, drakkar.oar.slice.server.ServerSidePrxHolder server, java.util.Map<String, String> __ctx)
        throws drakkar.oar.slice.error.RequestException;

    public Ice.AsyncResult begin_login(drakkar.oar.Seeker memb, drakkar.oar.slice.client.ClientSidePrx client);

    public Ice.AsyncResult begin_login(drakkar.oar.Seeker memb, drakkar.oar.slice.client.ClientSidePrx client, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_login(drakkar.oar.Seeker memb, drakkar.oar.slice.client.ClientSidePrx client, Ice.Callback __cb);

    public Ice.AsyncResult begin_login(drakkar.oar.Seeker memb, drakkar.oar.slice.client.ClientSidePrx client, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_login(drakkar.oar.Seeker memb, drakkar.oar.slice.client.ClientSidePrx client, Callback_Role_login __cb);

    public Ice.AsyncResult begin_login(drakkar.oar.Seeker memb, drakkar.oar.slice.client.ClientSidePrx client, java.util.Map<String, String> __ctx, Callback_Role_login __cb);

    public void end_login(drakkar.oar.slice.server.ServerSidePrxHolder server, Ice.AsyncResult __result)
        throws drakkar.oar.slice.error.RequestException;

    public void disconnect();

    public void disconnect(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_disconnect();

    public Ice.AsyncResult begin_disconnect(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_disconnect(Ice.Callback __cb);

    public Ice.AsyncResult begin_disconnect(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_disconnect(Callback_Role_disconnect __cb);

    public Ice.AsyncResult begin_disconnect(java.util.Map<String, String> __ctx, Callback_Role_disconnect __cb);

    public void end_disconnect(Ice.AsyncResult __result);
}
