// **********************************************************************
//
// Copyright (c) 2003-2010 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************

// Ice version 3.4.0

package drakkar.oar.slice;

// <auto-generated>
//
// Generated from file `Oar.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>


public final class SeekerHelper
{
    public static void
    write(IceInternal.BasicStream __os, drakkar.oar.Seeker __v)
    {
        __os.writeSerializable(__v);
    }

    public static drakkar.oar.Seeker
    read(IceInternal.BasicStream __is)
    {
        drakkar.oar.Seeker __v;
        __v = (drakkar.oar.Seeker)__is.readSerializable();
        return __v;
    }
}
