// **********************************************************************
//
// Copyright (c) 2003-2010 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************

// Ice version 3.4.0

package drakkar.oar.slice.management;

// <auto-generated>
//
// Generated from file `Administration.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>


public abstract class _ManagerDisp extends Ice.ObjectImpl implements Manager
{
    protected void
    ice_copyStateFrom(Ice.Object __obj)
        throws java.lang.CloneNotSupportedException
    {
        throw new java.lang.CloneNotSupportedException();
    }

    public static final String[] __ids =
    {
        "::Ice::Object",
        "::drakkar::oar::slice::action::RCPOperations",
        "::drakkar::oar::slice::action::oneway::Send",
        "::drakkar::oar::slice::action::twoway::Get",
        "::drakkar::oar::slice::management::Manager"
    };

    public boolean
    ice_isA(String s)
    {
        return java.util.Arrays.binarySearch(__ids, s) >= 0;
    }

    public boolean
    ice_isA(String s, Ice.Current __current)
    {
        return java.util.Arrays.binarySearch(__ids, s) >= 0;
    }

    public String[]
    ice_ids()
    {
        return __ids;
    }

    public String[]
    ice_ids(Ice.Current __current)
    {
        return __ids;
    }

    public String
    ice_id()
    {
        return __ids[4];
    }

    public String
    ice_id(Ice.Current __current)
    {
        return __ids[4];
    }

    public static String
    ice_staticId()
    {
        return __ids[4];
    }

    public final void
    sendAMID_async(drakkar.oar.slice.action.oneway.AMD_Send_sendAMID __cb, byte[] request)
        throws drakkar.oar.slice.error.RequestException
    {
        sendAMID_async(__cb, request, null);
    }

    public final void
    sendSAMI(byte[] request)
        throws drakkar.oar.slice.error.RequestException
    {
        sendSAMI(request, null);
    }

    public final void
    getAMID_async(drakkar.oar.slice.action.twoway.AMD_Get_getAMID __cb, byte[] request)
        throws drakkar.oar.slice.error.RequestException
    {
        getAMID_async(__cb, request, null);
    }

    public final byte[]
    getSAMI(byte[] request)
        throws drakkar.oar.slice.error.RequestException
    {
        return getSAMI(request, null);
    }

    private final static String[] __all =
    {
        "getAMID",
        "getSAMI",
        "ice_id",
        "ice_ids",
        "ice_isA",
        "ice_ping",
        "sendAMID",
        "sendSAMI"
    };

    public Ice.DispatchStatus
    __dispatch(IceInternal.Incoming in, Ice.Current __current)
    {
        int pos = java.util.Arrays.binarySearch(__all, __current.operation);
        if(pos < 0)
        {
            throw new Ice.OperationNotExistException(__current.id, __current.facet, __current.operation);
        }

        switch(pos)
        {
            case 0:
            {
                return drakkar.oar.slice.action.twoway._GetDisp.___getAMID(this, in, __current);
            }
            case 1:
            {
                return drakkar.oar.slice.action.twoway._GetDisp.___getSAMI(this, in, __current);
            }
            case 2:
            {
                return ___ice_id(this, in, __current);
            }
            case 3:
            {
                return ___ice_ids(this, in, __current);
            }
            case 4:
            {
                return ___ice_isA(this, in, __current);
            }
            case 5:
            {
                return ___ice_ping(this, in, __current);
            }
            case 6:
            {
                return drakkar.oar.slice.action.oneway._SendDisp.___sendAMID(this, in, __current);
            }
            case 7:
            {
                return drakkar.oar.slice.action.oneway._SendDisp.___sendSAMI(this, in, __current);
            }
        }

        assert(false);
        throw new Ice.OperationNotExistException(__current.id, __current.facet, __current.operation);
    }

    public void
    __write(IceInternal.BasicStream __os)
    {
        __os.writeTypeId(ice_staticId());
        __os.startWriteSlice();
        __os.endWriteSlice();
        super.__write(__os);
    }

    public void
    __read(IceInternal.BasicStream __is, boolean __rid)
    {
        if(__rid)
        {
            __is.readTypeId();
        }
        __is.startReadSlice();
        __is.endReadSlice();
        super.__read(__is, true);
    }

    public void
    __write(Ice.OutputStream __outS)
    {
        Ice.MarshalException ex = new Ice.MarshalException();
        ex.reason = "type drakkar::oar::slice::management::Manager was not generated with stream support";
        throw ex;
    }

    public void
    __read(Ice.InputStream __inS, boolean __rid)
    {
        Ice.MarshalException ex = new Ice.MarshalException();
        ex.reason = "type drakkar::oar::slice::management::Manager was not generated with stream support";
        throw ex;
    }
}
