// **********************************************************************
//
// Copyright (c) 2003-2010 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************

// Ice version 3.4.0

package drakkar.oar.slice.management;

// <auto-generated>
//
// Generated from file `Server.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>


public abstract class Callback_ServerManager_getManager extends Ice.TwowayCallback
{
    public abstract void response(ManagerPrx __ret);

    public final void __completed(Ice.AsyncResult __result)
    {
        ServerManagerPrx __proxy = (ServerManagerPrx)__result.getProxy();
        ManagerPrx __ret = null;
        try
        {
            __ret = __proxy.end_getManager(__result);
        }
        catch(Ice.LocalException __ex)
        {
            exception(__ex);
            return;
        }
        response(__ret);
    }
}
