// **********************************************************************
//
// Copyright (c) 2003-2010 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************

// Ice version 3.4.0

package drakkar.oar.slice.management;

// <auto-generated>
//
// Generated from file `Administration.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>


public interface Manager extends Ice.Object,
                                 _ManagerOperations, _ManagerOperationsNC,
                                 drakkar.oar.slice.action.RCPOperations
{
}
