// **********************************************************************
//
// Copyright (c) 2003-2010 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************

// Ice version 3.4.0

package drakkar.oar.slice.management;

// <auto-generated>
//
// Generated from file `Server.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>


public final class ServerManagerPrxHelper extends Ice.ObjectPrxHelperBase implements ServerManagerPrx
{
    public ManagerPrx
    getManager()
    {
        return getManager(null, false);
    }

    public ManagerPrx
    getManager(java.util.Map<String, String> __ctx)
    {
        return getManager(__ctx, true);
    }

    private ManagerPrx
    getManager(java.util.Map<String, String> __ctx, boolean __explicitCtx)
    {
        if(__explicitCtx && __ctx == null)
        {
            __ctx = _emptyContext;
        }
        int __cnt = 0;
        while(true)
        {
            Ice._ObjectDel __delBase = null;
            try
            {
                __checkTwowayOnly("getManager");
                __delBase = __getDelegate(false);
                _ServerManagerDel __del = (_ServerManagerDel)__delBase;
                return __del.getManager(__ctx);
            }
            catch(IceInternal.LocalExceptionWrapper __ex)
            {
                __handleExceptionWrapper(__delBase, __ex);
            }
            catch(Ice.LocalException __ex)
            {
                __cnt = __handleException(__delBase, __ex, null, __cnt);
            }
        }
    }

    private static final String __getManager_name = "getManager";

    public Ice.AsyncResult begin_getManager()
    {
        return begin_getManager(null, false, null);
    }

    public Ice.AsyncResult begin_getManager(java.util.Map<String, String> __ctx)
    {
        return begin_getManager(__ctx, true, null);
    }

    public Ice.AsyncResult begin_getManager(Ice.Callback __cb)
    {
        return begin_getManager(null, false, __cb);
    }

    public Ice.AsyncResult begin_getManager(java.util.Map<String, String> __ctx, Ice.Callback __cb)
    {
        return begin_getManager(__ctx, true, __cb);
    }

    public Ice.AsyncResult begin_getManager(Callback_ServerManager_getManager __cb)
    {
        return begin_getManager(null, false, __cb);
    }

    public Ice.AsyncResult begin_getManager(java.util.Map<String, String> __ctx, Callback_ServerManager_getManager __cb)
    {
        return begin_getManager(__ctx, true, __cb);
    }

    private Ice.AsyncResult begin_getManager(java.util.Map<String, String> __ctx, boolean __explicitCtx, IceInternal.CallbackBase __cb)
    {
        __checkAsyncTwowayOnly(__getManager_name);
        IceInternal.OutgoingAsync __result = new IceInternal.OutgoingAsync(this, __getManager_name, __cb);
        try
        {
            __result.__prepare(__getManager_name, Ice.OperationMode.Normal, __ctx, __explicitCtx);
            IceInternal.BasicStream __os = __result.__os();
            __os.endWriteEncaps();
            __result.__send(true);
        }
        catch(Ice.LocalException __ex)
        {
            __result.__exceptionAsync(__ex);
        }
        return __result;
    }

    public ManagerPrx end_getManager(Ice.AsyncResult __result)
    {
        Ice.AsyncResult.__check(__result, this, __getManager_name);
        if(!__result.__wait())
        {
            try
            {
                __result.__throwUserException();
            }
            catch(Ice.UserException __ex)
            {
                throw new Ice.UnknownUserException(__ex.ice_name());
            }
        }
        ManagerPrx __ret;
        IceInternal.BasicStream __is = __result.__is();
        __is.startReadEncaps();
        __ret = ManagerPrxHelper.__read(__is);
        __is.endReadEncaps();
        return __ret;
    }

    public static ServerManagerPrx
    checkedCast(Ice.ObjectPrx __obj)
    {
        ServerManagerPrx __d = null;
        if(__obj != null)
        {
            try
            {
                __d = (ServerManagerPrx)__obj;
            }
            catch(ClassCastException ex)
            {
                if(__obj.ice_isA("::drakkar::oar::slice::management::ServerManager"))
                {
                    ServerManagerPrxHelper __h = new ServerManagerPrxHelper();
                    __h.__copyFrom(__obj);
                    __d = __h;
                }
            }
        }
        return __d;
    }

    public static ServerManagerPrx
    checkedCast(Ice.ObjectPrx __obj, java.util.Map<String, String> __ctx)
    {
        ServerManagerPrx __d = null;
        if(__obj != null)
        {
            try
            {
                __d = (ServerManagerPrx)__obj;
            }
            catch(ClassCastException ex)
            {
                if(__obj.ice_isA("::drakkar::oar::slice::management::ServerManager", __ctx))
                {
                    ServerManagerPrxHelper __h = new ServerManagerPrxHelper();
                    __h.__copyFrom(__obj);
                    __d = __h;
                }
            }
        }
        return __d;
    }

    public static ServerManagerPrx
    checkedCast(Ice.ObjectPrx __obj, String __facet)
    {
        ServerManagerPrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            try
            {
                if(__bb.ice_isA("::drakkar::oar::slice::management::ServerManager"))
                {
                    ServerManagerPrxHelper __h = new ServerManagerPrxHelper();
                    __h.__copyFrom(__bb);
                    __d = __h;
                }
            }
            catch(Ice.FacetNotExistException ex)
            {
            }
        }
        return __d;
    }

    public static ServerManagerPrx
    checkedCast(Ice.ObjectPrx __obj, String __facet, java.util.Map<String, String> __ctx)
    {
        ServerManagerPrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            try
            {
                if(__bb.ice_isA("::drakkar::oar::slice::management::ServerManager", __ctx))
                {
                    ServerManagerPrxHelper __h = new ServerManagerPrxHelper();
                    __h.__copyFrom(__bb);
                    __d = __h;
                }
            }
            catch(Ice.FacetNotExistException ex)
            {
            }
        }
        return __d;
    }

    public static ServerManagerPrx
    uncheckedCast(Ice.ObjectPrx __obj)
    {
        ServerManagerPrx __d = null;
        if(__obj != null)
        {
            try
            {
                __d = (ServerManagerPrx)__obj;
            }
            catch(ClassCastException ex)
            {
                ServerManagerPrxHelper __h = new ServerManagerPrxHelper();
                __h.__copyFrom(__obj);
                __d = __h;
            }
        }
        return __d;
    }

    public static ServerManagerPrx
    uncheckedCast(Ice.ObjectPrx __obj, String __facet)
    {
        ServerManagerPrx __d = null;
        if(__obj != null)
        {
            Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
            ServerManagerPrxHelper __h = new ServerManagerPrxHelper();
            __h.__copyFrom(__bb);
            __d = __h;
        }
        return __d;
    }

    protected Ice._ObjectDelM
    __createDelegateM()
    {
        return new _ServerManagerDelM();
    }

    protected Ice._ObjectDelD
    __createDelegateD()
    {
        return new _ServerManagerDelD();
    }

    public static void
    __write(IceInternal.BasicStream __os, ServerManagerPrx v)
    {
        __os.writeProxy(v);
    }

    public static ServerManagerPrx
    __read(IceInternal.BasicStream __is)
    {
        Ice.ObjectPrx proxy = __is.readProxy();
        if(proxy != null)
        {
            ServerManagerPrxHelper result = new ServerManagerPrxHelper();
            result.__copyFrom(proxy);
            return result;
        }
        return null;
    }
}
