// **********************************************************************
//
// Copyright (c) 2003-2010 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************

// Ice version 3.4.0

package drakkar.oar.slice.action;

// <auto-generated>
//
// Generated from file `CollaborativeOperations.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>


public interface RCPOperations extends Ice.Object,
                                       _RCPOperationsOperations, _RCPOperationsOperationsNC,
                                       drakkar.oar.slice.action.oneway.Send,
                                       drakkar.oar.slice.action.twoway.Get
{
}
