// **********************************************************************
//
// Copyright (c) 2003-2010 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************

// Ice version 3.4.0

package drakkar.oar.slice.action.oneway;

// <auto-generated>
//
// Generated from file `Oneway.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>


final class _AMD_Send_sendAMID extends IceInternal.IncomingAsync implements AMD_Send_sendAMID
{
    public
    _AMD_Send_sendAMID(IceInternal.Incoming in)
    {
        super(in);
    }

    public void
    ice_response()
    {
        if(__validateResponse(true))
        {
            __response(true);
        }
    }

    public void
    ice_exception(java.lang.Exception ex)
    {
        try
        {
            throw ex;
        }
        catch(drakkar.oar.slice.error.RequestException __ex)
        {
            if(__validateResponse(false))
            {
                __os().writeUserException(__ex);
                __response(false);
            }
        }
        catch(java.lang.Exception __ex)
        {
            super.ice_exception(__ex);
        }
    }
}
