// **********************************************************************
//
// Copyright (c) 2003-2010 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************

// Ice version 3.4.0

package drakkar.oar.slice.action.oneway;

// <auto-generated>
//
// Generated from file `Oneway.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>


public interface _SendDel extends Ice._ObjectDel
{
    void sendSAMI(byte[] request, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper,
               drakkar.oar.slice.error.RequestException;

    void sendAMID(byte[] request, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper,
               drakkar.oar.slice.error.RequestException;
}
