// **********************************************************************
//
// Copyright (c) 2003-2010 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************

// Ice version 3.4.0

package drakkar.oar.slice.action.oneway;

// <auto-generated>
//
// Generated from file `Oneway.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>


public interface SendPrx extends Ice.ObjectPrx
{
    public void sendSAMI(byte[] request)
        throws drakkar.oar.slice.error.RequestException;

    public void sendSAMI(byte[] request, java.util.Map<String, String> __ctx)
        throws drakkar.oar.slice.error.RequestException;

    public Ice.AsyncResult begin_sendSAMI(byte[] request);

    public Ice.AsyncResult begin_sendSAMI(byte[] request, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_sendSAMI(byte[] request, Ice.Callback __cb);

    public Ice.AsyncResult begin_sendSAMI(byte[] request, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_sendSAMI(byte[] request, Callback_Send_sendSAMI __cb);

    public Ice.AsyncResult begin_sendSAMI(byte[] request, java.util.Map<String, String> __ctx, Callback_Send_sendSAMI __cb);

    public void end_sendSAMI(Ice.AsyncResult __result)
        throws drakkar.oar.slice.error.RequestException;

    public boolean sendSAMI_async(AMI_Send_sendSAMI __cb, byte[] request);

    public boolean sendSAMI_async(AMI_Send_sendSAMI __cb, byte[] request, java.util.Map<String, String> __ctx);

    public void sendAMID(byte[] request)
        throws drakkar.oar.slice.error.RequestException;

    public void sendAMID(byte[] request, java.util.Map<String, String> __ctx)
        throws drakkar.oar.slice.error.RequestException;

    public Ice.AsyncResult begin_sendAMID(byte[] request);

    public Ice.AsyncResult begin_sendAMID(byte[] request, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_sendAMID(byte[] request, Ice.Callback __cb);

    public Ice.AsyncResult begin_sendAMID(byte[] request, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_sendAMID(byte[] request, Callback_Send_sendAMID __cb);

    public Ice.AsyncResult begin_sendAMID(byte[] request, java.util.Map<String, String> __ctx, Callback_Send_sendAMID __cb);

    public void end_sendAMID(Ice.AsyncResult __result)
        throws drakkar.oar.slice.error.RequestException;

    public boolean sendAMID_async(AMI_Send_sendAMID __cb, byte[] request);

    public boolean sendAMID_async(AMI_Send_sendAMID __cb, byte[] request, java.util.Map<String, String> __ctx);
}
