// **********************************************************************
//
// Copyright (c) 2003-2010 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************

// Ice version 3.4.0

package drakkar.oar.slice.server;

// <auto-generated>
//
// Generated from file `ServerSide.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>


public interface _ServerSideDel extends drakkar.oar.slice.action._RCPOperationsDel
{
    void disconnect(java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;
}
